### ISSUE TITLE
`onSnapshot()` destructures subscribes resulting in different behavior then Firebase

### ISSUE THREAD

**Issue by wSedlacek** [gustavohenke/mockbase#20]
Code in question:
https://github.com/gustavohenke/mockbase/blob/f5b0184c6f9f98a2a904b91d7d8aab45ebb4e191/firestore/document-reference.ts#L142-L174

Example on how it is used from firebase in AngularFire
```ts
  return new Observable(subscriber => {
    let unsubscribe;
    if (scheduler != null) {
      scheduler.schedule(() => {
        unsubscribe = ref.onSnapshot(subscriber);
      });
    } else {
      unsubscribe = ref.onSnapshot(subscriber);
    }

    return () => {
      if (unsubscribe != null) {
        unsubscribe();
      }
    };
  });
```

By destructuring the subscriber it results in this error.
```
Unhandled Promise rejection: Cannot read property 'isStopped' of undefined ; Zone: ProxyZone ; Task: Promise.then ; Value: TypeError: Cannot read property 'isStopped' of undefined
```

Because `next()` references `this` internally in the RxJS subscriber it needs to be called with dot notation of the subscriber.

**Comment by gustavohenke** [comment]
Nice catch! Thanks for finding it :)
